prompt = "STARSHIP_SHELL= starship prompt"
table_mode = "thin"
history_duplicates = "ignoreconsecutive"
startup = [
        "alias la = lsd -la",
        "alias ct = cointop",
        "alias rain = rusty-rain",
        "alias rainj = rusty-rain -c jap",
        "alias dt = date now",
        "alias pg = ping google.de",
        "alias wtr = curl wttr.in/~oldenburg",

        "def fmt [] { cargo +nightly fmt --all }",
        "def udeps [] { cargo +nightly udeps --all-targets }",
        "def ssh_aws [] { ssh -i /home/magewe/aws_ssh_key_pair.pem ubuntu@ec2-3-101-22-91.us-west-1.compute.amazonaws.com }",
        "def mnt_bac [] { sudo cryptsetup luksOpen /dev/sdc1 backup; sudo mount /dev/mapper/backup /mnt/backup; }",
        "def mnt_surv [] { sudo zpool import; sudo zpool import surv_pool; sudo zfs mount -l surv_pool/enc }",
        "def night [] { redshift -O 4000 }",
        "def date_turk [] { date now | date to-timezone Turkey }",
        "def sk_rg [] { sk --ansi -i -c 'rg --color=always --line-number \"{}\"' }",
        "def dir_count [] { lsd -la | grep ^d | wc -l }",

        "cd ~",
]
